name: Deploy to Awardspace

on:
  push:
    branches:
      - main
    paths:
      - 'govassist_backend/**'
  workflow_dispatch:

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: 🔨 Flatten Backend
      shell: pwsh
      run: |
        ./.github/scripts/build.ps1

    - name: 📂 Sync files via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./dist/
        server-dir: /
